sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js
os:
  - linux
  - osx
node_js:
  - "4"
  - "3.2"
  - "2"
  - "1"
  - "0.12"
  - "0.11"
  - "0.10"

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test
